# Generated by Django 3.0 on 2019-12-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='post_connected',
            new_name='tweet_connected',
        ),
    ]
