# Generated by Django 3.0 on 2019-12-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20191212_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
